CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE clients(
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(15) NOT NULL,
    phone VARCHAR(15) NOT NULL UNIQUE
);